spring:
  datasource:
    url: jdbc:mysql://localhost:3306/BankApp
    username: root
    password: 10102002
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

server:
  port: 8080
